package server

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	pb "github.com/DeploCloud/deplo-agent/gen"
	"github.com/DeploCloud/deplo-agent/internal/dockercli"
)

type e2eBuildRecorder struct {
	mu       sync.Mutex
	commands []string
	infos    []string
}

func (r *e2eBuildRecorder) emitter() *emitter {
	return &emitter{send: func(ev *pb.DeployEvent) error {
		l := ev.GetLog()
		if l == nil {
			return nil
		}
		r.mu.Lock()
		defer r.mu.Unlock()
		switch l.GetLevel() {
		case "command":
			r.commands = append(r.commands, l.GetText())
		default:
			r.infos = append(r.infos, l.GetText())
		}
		return nil
	}}
}

func (r *e2eBuildRecorder) joined() string {
	r.mu.Lock()
	defer r.mu.Unlock()
	return strings.Join(append(append([]string{}, r.commands...), r.infos...), "\n")
}

func e2eToolsBase(t *testing.T) string {
	t.Helper()
	base := filepath.Join(os.TempDir(), "deplo-agent-e2e-tools")
	if err := os.MkdirAll(base, 0o755); err != nil {
		t.Fatal(err)
	}
	return base
}

// End-to-end (real docker): a railpack build must go through the daemon's own BuildKit - plan generated by the host binary, executed by the railpack frontend selected with BUILDKIT_SYNTAX, and land a LABELLED image in the image store in one pass.
func TestE2E_RailpackBuildsLabelledImageWithoutBuildkitdContainer(t *testing.T) {
	ctx := context.Background()
	if !dockercli.Available(ctx) {
		t.Skip("docker not available")
	}
	if !dockercli.ImageExportOptsSupported(ctx) {
		t.Skip("railpack's frontend needs the containerd image store (mergeop); this daemon uses the classic store")
	}
	s := New(t.TempDir(), t.TempDir(), "/", e2eToolsBase(t))

	buildDir := t.TempDir()
	write := func(name, body string) {
		if err := os.WriteFile(filepath.Join(buildDir, name), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("package.json", `{"name":"e2e-railpack","version":"1.0.0","scripts":{"build":"node -e \"require('fs').writeFileSync('baked.txt', process.env.NEXT_PUBLIC_API||'MISSING')\"","start":"node server.js"}}`)
	write("server.js", `require("http").createServer((_,r)=>r.end("ok")).listen(3000);`)

	const image = "deplo-test/railpack:e2e"
	const value = "https://api.example.test/v1"
	req := &pb.DeployRequest{
		Slug:      "railpacke2e",
		ProjectId: "prj_railpacke2e",
		ImageRef:  image,
		BuildKind: pb.BuildKind_BUILD_KIND_RAILPACK,
		BuildSpec: &pb.BuildSpec{Method: "railpack", Port: 3000},
		Env:       map[string]string{"NEXT_PUBLIC_API": value},
	}

	rec := &e2eBuildRecorder{}
	if !s.buildImage(ctx, req, buildDir, rec.emitter()) {
		t.Fatalf("railpack build failed; log:\n%s", rec.joined())
	}
	defer func() { _, _ = dockercli.Run(context.Background(), 60*time.Second, "rmi", "-f", image) }()

	labels, err := dockercli.Run(ctx, 30*time.Second, "image", "inspect", image,
		"--format", "{{index .Config.Labels \"deplo.managed\"}}/{{index .Config.Labels \"deplo.slug\"}}")
	if err != nil || labels.Code != 0 {
		t.Fatalf("inspect labels: %v %s", err, labels.Stderr)
	}
	if got := strings.TrimSpace(labels.Stdout); got != "true/railpacke2e" {
		t.Fatalf("labels = %q; want true/railpacke2e (frontend output must be labelled in one pass)", got)
	}

	baked, err := dockercli.Run(ctx, 60*time.Second, "run", "--rm", "--entrypoint", "cat", image, "/app/baked.txt")
	if err != nil || baked.Code != 0 {
		t.Fatalf("read baked file: %v %s", err, baked.Stderr)
	}
	if got := strings.TrimSpace(baked.Stdout); got != value {
		t.Fatalf("build-time env = %q; want %q", got, value)
	}

	log := rec.joined()
	for _, forbidden := range []string{"deplo-buildkitd-", "docker load", "buildctl", "apt-get"} {
		if strings.Contains(log, forbidden) {
			t.Fatalf("railpack still uses %q; log:\n%s", forbidden, log)
		}
	}
	ps, err := dockercli.Run(ctx, 30*time.Second, "ps", "-a", "--filter", "name=deplo-buildkitd-", "-q")
	if err == nil && strings.TrimSpace(ps.Stdout) != "" {
		t.Fatalf("a buildkitd container was left behind: %s", ps.Stdout)
	}

	if strings.Contains(strings.Join(rec.commands, "\n"), value) {
		t.Fatalf("build-env value leaked into a logged command: %v", rec.commands)
	}
}

// End-to-end (real docker): a build must ask for the fast image export exactly when the daemon can take it.
func TestE2E_BuildAsksForFastExportWhenSupported(t *testing.T) {
	ctx := context.Background()
	if !dockercli.Available(ctx) {
		t.Skip("docker not available")
	}
	s := New(t.TempDir(), t.TempDir(), "/", "")
	buildDir := t.TempDir()

	const image = "deplo-test/fastexport:e2e"
	req := &pb.DeployRequest{
		Slug:       "fastexport",
		ProjectId:  "prj_fastexport",
		ImageRef:   image,
		BuildKind:  pb.BuildKind_BUILD_KIND_DOCKERFILE,
		Dockerfile: &pb.DockerfileBuild{Generated: true, GeneratedDockerfile: "FROM busybox\nCMD [\"true\"]\n"},
	}

	rec := &e2eBuildRecorder{}
	if !s.buildImage(ctx, req, buildDir, rec.emitter()) {
		t.Fatalf("build failed; log:\n%s", rec.joined())
	}
	defer func() { _, _ = dockercli.Run(context.Background(), 30*time.Second, "rmi", "-f", image) }()

	cmds := strings.Join(rec.commands, "\n")
	if dockercli.ImageExportOptsSupported(ctx) {
		want := "--output type=image,name=" + image + ",compression=zstd,compression-level=1"
		if !strings.Contains(cmds, want) {
			t.Fatalf("containerd store present but the build did not ask for the fast export.\nwant: %s\ngot:  %s", want, cmds)
		}
	} else if !strings.Contains(cmds, "-t "+image) {
		t.Fatalf("no image exporter available, so the build must use -t; got: %s", cmds)
	}

	res, err := dockercli.Run(ctx, 30*time.Second, "image", "inspect", image, "--format", "{{.Id}}")
	if err != nil || res.Code != 0 {
		t.Fatalf("built image is not in the image store: %v %s", err, res.Stderr)
	}
}
